### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by BastiKarg** [rvalieris/parallel-fastq-dump#1]
Hello I want to use your parrallel-fastq-dump as it would help my a lot in my studies. 
It seems I have issues using the right syntax somehow... Every time I try to use it I get the ERROR:
File "/home/hpc/t1172/di36dih/bin/parallel-fastq-dump", line 29
    p = subprocess.Popen(["fastq-dump", "-N", str(out[i][0]), "-X", str(out[i][1]), "-O", d, *extra_args, args.sra_id]) 
Could you send one or two example calls so I understand my problem? 

Thanks in advance,
Sincerly TripleB

**Comment by rvalieris** [comment]
Hello there, could you post the entire exception message ?

here are a few examples:
```
$ parallel-fastq-dump --sra-id SRR1219899 --threads 4 --outdir out
$ parallel-fastq-dump --sra-id SRR1219899 --threads 4 --outdir out/ --split-files --gzip
```

keep in mind that you need python3 to run the script, and you need `fastq-dump` and `sra-stat` in your path.

see also the help message:
```
$ parallel-fastq-dump -h
usage: parallel-fastq-dump [-h] [-s SRA_ID] [-t THREADS] [-O OUTDIR]
                           [--tmpdir TMPDIR] [-V]

parallel fastq-dump wrapper, extra args will be passed through

optional arguments:
  -h, --help            show this help message and exit
  -s SRA_ID, --sra-id SRA_ID
                        SRA id
  -t THREADS, --threads THREADS
                        number of threads
  -O OUTDIR, --outdir OUTDIR
                        output directory
  --tmpdir TMPDIR       temporary directory
  -V, --version         shows version
```

**Comment by BastiKarg** [comment]
That is already the complete error-message. But I noticed that I don't have
sra-stat installed... I will install sra.-stat and try it again. I am sorry
bothering you with this mistake of mine! Thank you very much for your fast
answer!

**Comment by rvalieris** [comment]
Don't worry about it !

Doesn't it have a message like "SyntaxError: invalid syntax" ?
if so I suspect you are running the script with python2. You need to use python3.
