### ISSUE TITLE
Cannot find temporary files

### ISSUE THREAD

**Issue by devmon** [rvalieris/parallel-fastq-dump#11]
So the program creates temporary files in /tmp/pfd_0hm17d1p but at the end, it cannot find the second fastq file: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pfd_0hm17d1p/10/SRR4253583_2.fastq'

$ parallel-fastq-dump --sra-id SRR4253583 -t 16 -O out/ --split-files
SRR ids: ['SRR4253583']
extra args: ['--split-files']
SRR4253583 spots: 143228176
tempdir: /tmp/pfd_0hm17d1p
blocks: [[1, 8951761], [8951762, 17903522], [17903523, 26855283], [26855284, 35807044], [35807045, 44758805], [44758806, 53710566], [53710567, 62662327], [62662328, 71614088], [71614089, 80565849], [80565850, 89517610], [89517611, 98469371], [98469372, 107421132], [107421133, 116372893], [116372894, 125324654], [125324655, 134276415], [134276416, 143228176]]Rejected 8951761 READS because READLEN < 1
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Rejected 8951761 READS because READLEN < 1
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Rejected 8951761 READS because READLEN < 1
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Rejected 8951761 READS because READLEN < 1
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Rejected 8951761 READS because READLEN < 1
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Rejected 8951761 READS because READLEN < 1
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Rejected 1880687 READS because READLEN < 1
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Read 8951761 spots for SRR4253583
Written 8951761 spots for SRR4253583
Traceback (most recent call last):
  File "/home/$username/anaconda3/bin/parallel-fastq-dump", line 4, in <module>
    __import__('pkg_resources').run_script('parallel-fastq-dump==0.6.2', 'parallel-fastq-dump')
  File "/home/$username/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/$username/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/home/$username/anaconda3/lib/python3.6/site-packages/parallel_fastq_dump-0.6.2-py3.6.egg/EGG-INFO/scripts/parallel-fastq-dump", line 100, in <module>
  File "/home/$username/anaconda3/lib/python3.6/site-packages/parallel_fastq_dump-0.6.2-py3.6.egg/EGG-INFO/scripts/parallel-fastq-dump", line 93, in main
  File "/home/$username/anaconda3/lib/python3.6/site-packages/parallel_fastq_dump-0.6.2-py3.6.egg/EGG-INFO/scripts/parallel-fastq-dump", line 43, in pfd
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pfd_0hm17d1p/10/SRR4253583_2.fastq'

Thanks!

**Comment by rvalieris** [comment]
hello,

looks like, in this specific run, there are many reads being filtered out (`Rejected 1880687 READS because READLEN < 1`), and because of that not all blocks have both files `_1` and `_2`.

I will investigate this SRR and see what we can do.

**Comment by devmon** [comment]
It works with normal fastq-dump.

**Comment by rvalieris** [comment]
so, I was assuming all blocks of a SRR would have the same files, but in cases like this were lots of reads were filtered this is not true, in 0.6.3 I only merge the files present in each block.

**Comment by rvalieris** [comment]
0.6.3 is out with the fix

**Comment by devmon** [comment]
Thank you again!
