### ISSUE TITLE
conda install failed on MacOS X Yosemite 10.10.5

### ISSUE THREAD

**Issue by weihua77** [rvalieris/parallel-fastq-dump#12]
There are two parts of the error (given below), though they could be related:
1. Solving environment failed
2. PackageNotFoundError

Is this because the package is not available for Mac OS?

I did do "conda update conda" to make sure my conda is up to date (conda/4.5.0). 
And I tried install another package using conda and it worked fine. (conda install geopy)

Error message is given below:
**********************************************
$ conda install parallel-fastq-dump
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - parallel-fastq-dump

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
*****************************************************************

**Comment by rvalieris** [comment]
hello,

the package in on the [Bioconda](http://bioconda.github.io/) channel, use this command to add it:
`conda config --add channels bioconda`
