### ISSUE TITLE
point to a local file? 

### ISSUE THREAD

**Issue by Sames-Jtudd** [rvalieris/parallel-fastq-dump#14]
I have access to some restricted SRA files on dbGAP which I have downloaded. When executing $ parallel-fastq-dump -s SRR.sra I get an error message.

2018-05-08T14:34:42 fastq-dump.2.8.2 err: file not found while opening file within network system module - FailekeHttpFileInt('https://gap-download.be-md.ncbi.nlm.nih.gov/sragap/D3B39D27-6567-4F0A-87EA-2707BC243B8B/SRR100758B0E3F-7D85-4391-84B7-2C1B31A30C5B' (130.14.250.15))

It looks like the command is attempting to generate the fastq files from directly from the online SRA files. However as they are protected presumably it fails to find them, I have uploaded the correct ncg file 
for permission as per the instuctions on (https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=dbgap_use) to the new version of SRA tools bundled with parallel-fastq-dump. 

Is there any way to direct this command to a local file or other solution you may be able to suggest. 

Many thanks any help appreciated

james

**Comment by rvalieris** [comment]
hello,

for dbGAP protected files you have to do the dumping on the same directory you setup as "workspace" on vdb-config.

what I usually do is prefetch of the SRA files and follow with fastq-dump of the ID, as long as the sra file is in same directory prefetch used fastq-dump should pick it up instead of downloading it again.

**Comment by Sames-Jtudd** [comment]
Hi, 

thanks for getting back to me so quickly, got it working now.

cheers

**Comment by rvalieris** [comment]
I am glad to hear it. I will go ahead and close this then.
