### ISSUE TITLE
Problem with large files

### ISSUE THREAD

**Issue by apredeus** [rvalieris/parallel-fastq-dump#2]
Hello, 

thank you for the useful tool! I've used it for my projects with downloaded SRA files and things speed up quite a lot. However I've tried it on a very large file, e.g. SRR3192525 (a 30 Gb archive), and it made it crush with "not enough storage" message, while serial fastq-dump finished the job ok. 

Does it use default Python tmp directory or something like that? Maybe it would make sense to set tmp dir to the directory in which the tool is run?

**Comment by rvalieris** [comment]
hello,

yes by default it will use `tempfile.gettempdir()` which will probably be `/tmp`, but you can override this with the `--tmpdir` argument.

**Comment by apredeus** [comment]
Thank you, I've completely overlooked that option.

**Comment by rvalieris** [comment]
don't worry, I am glad the tool in being useful !
