### ISSUE TITLE
Forward and reverse identifier /1 and /2

### ISSUE THREAD

**Issue by smb20200615** [rvalieris/parallel-fastq-dump#31]
Hello,

Thank you for your wonderful tool. Is there any way I can download the reads with the forward and reverse identifiers? Some downstream applications require these identifiers.

Many thanks!!

**Comment by rvalieris** [comment]
hello,

please note that `parallel-fastq-dump` only calls `fastq-dump` under the hood, so we are limited by the options `fastq-dump` gives us.

with that said, you can use the option `--readids` which will add an extra `.1` /`.2` to the read name

**Comment by smb20200615** [comment]
Thank you so much!

**Comment by sskashaf** [comment]
Apologies. I am running into issues with bwa due to the .1, .2. Is there any way to change this to /1 and /2 when downloading from the SRA? Sed -i takes a really long time.

**Comment by smb20200615** [comment]
Apologies. Is there anyway to switch the .1 and .2 to /1 and /2 when downloading due to issues with bwa in downstream steps? sed -i takes a very long time

**Comment by rvalieris** [comment]
no, I don't think so.

but what you could do is, map the R1, R2 files with bwa as normal, and then later use picard [SamToFastq](https://broadinstitute.github.io/picard/command-line-overview.html#SamToFastq) with the INTERLEAVE option, to will create fastq with /1 and /2
