### ISSUE TITLE
fastq-dump uses network even though I prefectech

### ISSUE THREAD

**Issue by nh13** [rvalieris/parallel-fastq-dump#32]
I have `ERR3240205` and `ERR3240205.vdbcache` files retrieved through SRA Cloud Data Delivery.  I then ran:

```bash
parallel-fastq-dump -s ERR3240193 -t 2 -O out --tmpdir tmp --split-files --gzip
```

I found the two `fastq-dump` processes, and ran `strace -f -e trace=network -p <pid>` on each.  I found that the `fastq-dump` that starts from the start of the SRA file does not use network IO, while the one that starts mid-range does, and was wondering why given I've downloaded the file.

**Comment by rvalieris** [comment]
hello, can you add which version of fastq-dump are you using ?

if the prefetch completed it should not be using network, in my local tests strace does not give any results for either process, but I don't have much insight into how fastq-dump works internally.

**Comment by nh13** [comment]
Here's the versions:
```
$ parallel-fastq-dump --version
parallel-fastq-dump : 0.6.6

"fastq-dump" version 2.10.9
```

**Comment by rvalieris** [comment]
I'm using fastq-dump version 2.10.8, I don't think thats the reason, but you could try downgrading sra-tools.

also I just noticed you mention sra cloud data delivery, you [mean this](https://www.ncbi.nlm.nih.gov/sra/docs/sra-cloud/) I assume, I have not tested under these conditions, but I guess its possible sra-tools does something different in this case.

either way, to dig further into this I think its best to contact the [sra-tools devs](https://github.com/ncbi/sra-tools), if you havent already.
