### ISSUE TITLE
an integer is required (got type _io.BufferedWriter)

### ISSUE THREAD

**Issue by Divyoj-Singh** [rvalieris/parallel-fastq-dump#34]
Hi I am trying to use pfd for converting sra file to fastq files in a pipeline. I have a cluster with 100 cores.following is my code:
variable word1 has the SRR id.  

time $path_to_parallel_fastq_dump --threads 100 --sra-id $word1 --tmpdir $path_to_sra_folder --outdir $path_to_fastq_folder$word1.fastq |& tee $path_to_stats_folder/sra_fastq/fout1_$word1.txt

But, I am getting following error:
File "/home/csb/tools/parallel-fastq-dump-master/parallel-fastq-dump", line 123, in <module>
    main()
  File "/home/csb/tools/parallel-fastq-dump-master/parallel-fastq-dump", line 116, in main
    pfd(args, si, extra_args)
  File "/home/csb/tools/parallel-fastq-dump-master/parallel-fastq-dump", line 50, in pfd
    os.close(fd)
TypeError: an integer is required (got type _io.BufferedWriter)

Can you please help ?

**Comment by rvalieris** [comment]
hello, sorry, looks like https://github.com/rvalieris/parallel-fastq-dump/pull/33 introduced a bug, to fix, replace the line:
`os.close(fd)`
to
` fd.close()`

I will commit a fix soon.

also, `--outdir $path_to_fastq_folder$word1.fastq` 
`--outdir` should be a path to a directory, you don't have to add  `$word1.fastq` in the end

**Comment by Divyoj-Singh** [comment]
Thanks!!
Will check it out!
