### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by nick-youngblut** [rvalieris/parallel-fastq-dump#35]
If the user provides a temp directory that doesn't exist, then `parallel-fastq-dump` throws a `FileNotFoundError` error. How about including a `os.makedirs()` line to create the directory if it doesn't exist?

**Comment by rvalieris** [comment]
Hi, I agree, and I see you already included this change in the PR #37 thanks

**Comment by nick-youngblut** [comment]
Sorry for not noting the PR in this issue
