### ISSUE TITLE
What does it mean if -split-files is used but I still only get a single output file for each input file?

### ISSUE THREAD

**Issue by joepalermo** [rvalieris/parallel-fastq-dump#43]
Hi, this is more of a question about fastq, but not sure where I should go to get help with it. I would appreciate it if anyone here can help me!

**What does it mean if -split-files is used but I still only get a single output file (I..e I get ..._1.fastq but not ..._2.fastq)?** My understanding is that I should get 2 output files.

```
import os 
command = 'parallel-fastq-dump/parallel-fastq-dump '+\
 f'--outdir {data_dirpath}/sratofastq/{sra_id} '+\
'--threads 32 '+\
'--split-files '+\
'--tmpdir tmpdir '+\
f'-s {data_dirpath}/pysradb_downloads/{sra_id}/SRX2536403/SRR5227288.sra'
print(command)
print(os.system(command))
```

**Comment by rvalieris** [comment]
> What does it mean if -split-files is used but I still only get a single output file

most likely, the run is single-end, you can check this on the SRA website, https://www.ncbi.nlm.nih.gov/sra/?term=SRR5227288
you can see on the Library section, Layout: SINGLE

**Comment by joepalermo** [comment]
Ahh I see. Thanks!
