### ISSUE TITLE
can't install parallel-fastq-dump 

### ISSUE THREAD

**Issue by dmncyap** [rvalieris/parallel-fastq-dump#49]
I used conda install parallel-fastq-dump but I keep getting this error:

olving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - parallel-fastq-dump

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Is the package still there in conda? or was it removed?

**Comment by rvalieris** [comment]
hello,
the package is available in bioconda, follow the steps in this page to setup: https://bioconda.github.io/
