### ISSUE TITLE
parallel-fastq-dump can't download some old datasets

### ISSUE THREAD

**Issue by golobor** [rvalieris/parallel-fastq-dump#5]
Hi,
thank you for writing this neat tool - it nicely covers a critical gap in ncbi-tools!
I started using it in our lab's snakemake pipelines and found that it can't deal with some old datasets.
In particular, it froze when it tried to download SRR567536 (from https://www.ncbi.nlm.nih.gov/sra/SRX183520). I used the following command:
parallel-fastq-dump --origfmt --split-files --gzip -s SRR567537 -t 8  

At the same time, ncbi-tools can download it:
fastq-dump --origfmt --split-files --gzip SRR567536  

I also tried prefetch-ing and it didn't help.

Anton.

**Comment by rvalieris** [comment]
hello, thanks for the report.

ah yes, looks like I misunderstood the python docs, wait() is deadlocking with this dataset:

[Note](https://docs.python.org/3/library/subprocess.html#popen-objects)``
: This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that. 
``

I will commit a fix soon.

**Comment by rvalieris** [comment]
should be fixed on the new 0.6.1 version, give it a try !
