### ISSUE TITLE
The dependency sra-tools in conda is outdated and will trigger errors

### ISSUE THREAD

**Issue by DongzeHE** [rvalieris/parallel-fastq-dump#51]
When installing `parallel-fastq-dump` from conda, it will also pull a sra-tools v 2.8.0 from conda even if I have a local sra-tools. This sra-tools is outdated and will cause network connection error. This should be fixed

```

The following NEW packages will be INSTALLED:

  parallel-fastq-dump bioconda/noarch::parallel-fastq-dump-0.6.7-pyhdfd78af_0
  sra-tools          bioconda/linux-64::sra-tools-2.8.0-0


```

**Comment by rvalieris** [comment]
Hello,
this is most likely happening because you have other packages on the same env conflicting with the installation of newer version of sra-tools, try to install it on a separate env like this:

`conda create -n testenv parallel-fastq-dump 'sra-tools>=3.0.0'`

**Comment by DongzeHE** [comment]
Actually, this happened to me in a brand new conda env. But anyway, I just wanted to bring this to your attention because I used the [code in the README](https://github.com/rvalieris/parallel-fastq-dump#install) but it did not work. Thank you so much for your reply!

**Comment by rvalieris** [comment]
no problem, conda always tries to be conforming with the existing packages in your env so sometimes it will decide to install older versions of the package you asked so its good to watch out for this. I guess I can add a note about this on the readme.
