### ISSUE TITLE
Can it deal with local sra file?

### ISSUE THREAD

**Issue by shenweima** [rvalieris/parallel-fastq-dump#6]
I have several sra files in my computer, Can it deal with local sra file?

**Comment by rvalieris** [comment]
if the sra files were downloaded with prefetch you only have to pass the ids to the tool.

if the sra files are somewhere else you can pass the whole path to the tool, it will behave the same as fastq-dump would.

the only but is, be careful if you want to process multiple sra files at once, i fixed the code recently to deal with multiple SRR ids, but detecting arbitrary paths (eg. that don't contain "SRR") is not being handled right now.

the right way is:
``parallel-fastq-dump -s <file 1> -s <file 2> -s <file 3> [other args]``
